<?php declare(strict_types=1);

namespace OpenCCK\Kalman\Domain\Covariance\Kernels;

use OpenCCK\Kalman\Domain\Contract\CovarianceRepresentation;
use OpenCCK\Kalman\Domain\Contract\SparseMotionModel;
use OpenCCK\Kalman\Domain\Exception\DimensionMismatch;

/**
 * GENERATED by tools/generate-kernels.php — do not edit by hand.
 * Fully unrolled sequential-form covariance for n = 2 (§6.2 p.5):
 * no loops, no function calls; identical algebra to DenseSequential.
 */
final class Sequential2 implements CovarianceRepresentation
{
	/** @var array<int, float> n² */
	private array $P;

	/** @var array<int, float> n */
	private array $phi;

	private float $hPh = 0.0;

	public function __construct()
	{
		$this->P = \array_fill(0, 4, 0.0);
		$this->phi = \array_fill(0, 2, 0.0);
	}

	public function size(): int
	{
		return 2;
	}

	public function predictDense(array $F, array $Q): void
	{
		$P = &$this->P;
		$p0 = $P[0];
		$p1 = $P[1];
		$p2 = $P[2];
		$p3 = $P[3];
		$t0 = $F[0] * $p0 + $F[1] * $p2;
		$t1 = $F[0] * $p1 + $F[1] * $p3;
		$t2 = $F[2] * $p0 + $F[3] * $p2;
		$t3 = $F[2] * $p1 + $F[3] * $p3;
		$v = $Q[0] + $t0 * $F[0] + $t1 * $F[1];
		$P[0] = $v;
		$v = $Q[1] + $t0 * $F[2] + $t1 * $F[3];
		$P[1] = $v;
		$P[2] = $v;
		$v = $Q[3] + $t2 * $F[2] + $t3 * $F[3];
		$P[3] = $v;
	}

	public function predictSparse(SparseMotionModel $model, float $dt, array &$x, array $Q): void
	{
		$model->advanceInPlace($x, $this->P, $dt);
		$P = &$this->P;
		$P[0] += $Q[0];
		$v = $P[1] + $Q[1];
		$P[1] = $v;
		$P[2] = $v;
		$P[3] += $Q[3];
	}

	public function prepareScalar(array $h, float $r): float
	{
		$P = &$this->P;
		$phi = &$this->phi;
		$h0 = $h[0] ?? 0.0;
		$h1 = $h[1] ?? 0.0;
		$f0 = $P[0] * $h0 + $P[1] * $h1;
		$phi[0] = $f0;
		$f1 = $P[2] * $h0 + $P[3] * $h1;
		$phi[1] = $f1;
		$hPh = $h0 * $f0 + $h1 * $f1;
		$this->hPh = $hPh;
		return $hPh + $r;
	}

	public function gain(): array
	{
		return $this->phi;
	}

	public function commitScalar(float $r): void
	{
		$P = &$this->P;
		$phi = $this->phi;
		$inv = 1.0 / ($this->hPh + $r);
		$k0 = $phi[0] * $inv;
		$k1 = $phi[1] * $inv;
		$P[0] -= $k0 * $phi[0];
		$v = $P[1] - $k0 * $phi[1];
		$P[1] = $v;
		$P[2] = $v;
		$P[3] -= $k1 * $phi[1];
	}

	public function toDense(): array
	{
		return $this->P;
	}

	public function fromDense(array $P): void
	{
		if (\count($P) !== 4) {
			throw DimensionMismatch::forMatrix('P', 4, \count($P));
		}
		$dst = &$this->P;
		$v = (float) $P[0];
		$dst[0] = $v;
		$v = (float) $P[1];
		$dst[1] = $v;
		$dst[2] = $v;
		$v = (float) $P[3];
		$dst[3] = $v;
	}

	public function variance(int $i): float
	{
		return $this->P[$i * 2 + $i];
	}
}
