<?php declare(strict_types=1);

namespace OpenCCK\Kalman\Domain\Covariance\Kernels;

use OpenCCK\Kalman\Domain\Contract\CovarianceRepresentation;
use OpenCCK\Kalman\Domain\Contract\SparseMotionModel;
use OpenCCK\Kalman\Domain\Exception\DimensionMismatch;

/**
 * GENERATED by tools/generate-kernels.php — do not edit by hand.
 * Fully unrolled sequential-form covariance for n = 4 (§6.2 p.5):
 * no loops, no function calls; identical algebra to DenseSequential.
 */
final class Sequential4 implements CovarianceRepresentation
{
	/** @var array<int, float> n² */
	private array $P;

	/** @var array<int, float> n */
	private array $phi;

	private float $hPh = 0.0;

	public function __construct()
	{
		$this->P = \array_fill(0, 16, 0.0);
		$this->phi = \array_fill(0, 4, 0.0);
	}

	public function size(): int
	{
		return 4;
	}

	public function predictDense(array $F, array $Q): void
	{
		$P = &$this->P;
		$p0 = $P[0];
		$p1 = $P[1];
		$p2 = $P[2];
		$p3 = $P[3];
		$p4 = $P[4];
		$p5 = $P[5];
		$p6 = $P[6];
		$p7 = $P[7];
		$p8 = $P[8];
		$p9 = $P[9];
		$p10 = $P[10];
		$p11 = $P[11];
		$p12 = $P[12];
		$p13 = $P[13];
		$p14 = $P[14];
		$p15 = $P[15];
		$t0 = $F[0] * $p0 + $F[1] * $p4 + $F[2] * $p8 + $F[3] * $p12;
		$t1 = $F[0] * $p1 + $F[1] * $p5 + $F[2] * $p9 + $F[3] * $p13;
		$t2 = $F[0] * $p2 + $F[1] * $p6 + $F[2] * $p10 + $F[3] * $p14;
		$t3 = $F[0] * $p3 + $F[1] * $p7 + $F[2] * $p11 + $F[3] * $p15;
		$t4 = $F[4] * $p0 + $F[5] * $p4 + $F[6] * $p8 + $F[7] * $p12;
		$t5 = $F[4] * $p1 + $F[5] * $p5 + $F[6] * $p9 + $F[7] * $p13;
		$t6 = $F[4] * $p2 + $F[5] * $p6 + $F[6] * $p10 + $F[7] * $p14;
		$t7 = $F[4] * $p3 + $F[5] * $p7 + $F[6] * $p11 + $F[7] * $p15;
		$t8 = $F[8] * $p0 + $F[9] * $p4 + $F[10] * $p8 + $F[11] * $p12;
		$t9 = $F[8] * $p1 + $F[9] * $p5 + $F[10] * $p9 + $F[11] * $p13;
		$t10 = $F[8] * $p2 + $F[9] * $p6 + $F[10] * $p10 + $F[11] * $p14;
		$t11 = $F[8] * $p3 + $F[9] * $p7 + $F[10] * $p11 + $F[11] * $p15;
		$t12 = $F[12] * $p0 + $F[13] * $p4 + $F[14] * $p8 + $F[15] * $p12;
		$t13 = $F[12] * $p1 + $F[13] * $p5 + $F[14] * $p9 + $F[15] * $p13;
		$t14 = $F[12] * $p2 + $F[13] * $p6 + $F[14] * $p10 + $F[15] * $p14;
		$t15 = $F[12] * $p3 + $F[13] * $p7 + $F[14] * $p11 + $F[15] * $p15;
		$v = $Q[0] + $t0 * $F[0] + $t1 * $F[1] + $t2 * $F[2] + $t3 * $F[3];
		$P[0] = $v;
		$v = $Q[1] + $t0 * $F[4] + $t1 * $F[5] + $t2 * $F[6] + $t3 * $F[7];
		$P[1] = $v;
		$P[4] = $v;
		$v = $Q[2] + $t0 * $F[8] + $t1 * $F[9] + $t2 * $F[10] + $t3 * $F[11];
		$P[2] = $v;
		$P[8] = $v;
		$v = $Q[3] + $t0 * $F[12] + $t1 * $F[13] + $t2 * $F[14] + $t3 * $F[15];
		$P[3] = $v;
		$P[12] = $v;
		$v = $Q[5] + $t4 * $F[4] + $t5 * $F[5] + $t6 * $F[6] + $t7 * $F[7];
		$P[5] = $v;
		$v = $Q[6] + $t4 * $F[8] + $t5 * $F[9] + $t6 * $F[10] + $t7 * $F[11];
		$P[6] = $v;
		$P[9] = $v;
		$v = $Q[7] + $t4 * $F[12] + $t5 * $F[13] + $t6 * $F[14] + $t7 * $F[15];
		$P[7] = $v;
		$P[13] = $v;
		$v = $Q[10] + $t8 * $F[8] + $t9 * $F[9] + $t10 * $F[10] + $t11 * $F[11];
		$P[10] = $v;
		$v = $Q[11] + $t8 * $F[12] + $t9 * $F[13] + $t10 * $F[14] + $t11 * $F[15];
		$P[11] = $v;
		$P[14] = $v;
		$v = $Q[15] + $t12 * $F[12] + $t13 * $F[13] + $t14 * $F[14] + $t15 * $F[15];
		$P[15] = $v;
	}

	public function predictSparse(SparseMotionModel $model, float $dt, array &$x, array $Q): void
	{
		$model->advanceInPlace($x, $this->P, $dt);
		$P = &$this->P;
		$P[0] += $Q[0];
		$v = $P[1] + $Q[1];
		$P[1] = $v;
		$P[4] = $v;
		$v = $P[2] + $Q[2];
		$P[2] = $v;
		$P[8] = $v;
		$v = $P[3] + $Q[3];
		$P[3] = $v;
		$P[12] = $v;
		$P[5] += $Q[5];
		$v = $P[6] + $Q[6];
		$P[6] = $v;
		$P[9] = $v;
		$v = $P[7] + $Q[7];
		$P[7] = $v;
		$P[13] = $v;
		$P[10] += $Q[10];
		$v = $P[11] + $Q[11];
		$P[11] = $v;
		$P[14] = $v;
		$P[15] += $Q[15];
	}

	public function prepareScalar(array $h, float $r): float
	{
		$P = &$this->P;
		$phi = &$this->phi;
		$h0 = $h[0] ?? 0.0;
		$h1 = $h[1] ?? 0.0;
		$h2 = $h[2] ?? 0.0;
		$h3 = $h[3] ?? 0.0;
		$f0 = $P[0] * $h0 + $P[1] * $h1 + $P[2] * $h2 + $P[3] * $h3;
		$phi[0] = $f0;
		$f1 = $P[4] * $h0 + $P[5] * $h1 + $P[6] * $h2 + $P[7] * $h3;
		$phi[1] = $f1;
		$f2 = $P[8] * $h0 + $P[9] * $h1 + $P[10] * $h2 + $P[11] * $h3;
		$phi[2] = $f2;
		$f3 = $P[12] * $h0 + $P[13] * $h1 + $P[14] * $h2 + $P[15] * $h3;
		$phi[3] = $f3;
		$hPh = $h0 * $f0 + $h1 * $f1 + $h2 * $f2 + $h3 * $f3;
		$this->hPh = $hPh;
		return $hPh + $r;
	}

	public function gain(): array
	{
		return $this->phi;
	}

	public function commitScalar(float $r): void
	{
		$P = &$this->P;
		$phi = $this->phi;
		$inv = 1.0 / ($this->hPh + $r);
		$k0 = $phi[0] * $inv;
		$k1 = $phi[1] * $inv;
		$k2 = $phi[2] * $inv;
		$k3 = $phi[3] * $inv;
		$P[0] -= $k0 * $phi[0];
		$v = $P[1] - $k0 * $phi[1];
		$P[1] = $v;
		$P[4] = $v;
		$v = $P[2] - $k0 * $phi[2];
		$P[2] = $v;
		$P[8] = $v;
		$v = $P[3] - $k0 * $phi[3];
		$P[3] = $v;
		$P[12] = $v;
		$P[5] -= $k1 * $phi[1];
		$v = $P[6] - $k1 * $phi[2];
		$P[6] = $v;
		$P[9] = $v;
		$v = $P[7] - $k1 * $phi[3];
		$P[7] = $v;
		$P[13] = $v;
		$P[10] -= $k2 * $phi[2];
		$v = $P[11] - $k2 * $phi[3];
		$P[11] = $v;
		$P[14] = $v;
		$P[15] -= $k3 * $phi[3];
	}

	public function toDense(): array
	{
		return $this->P;
	}

	public function fromDense(array $P): void
	{
		if (\count($P) !== 16) {
			throw DimensionMismatch::forMatrix('P', 16, \count($P));
		}
		$dst = &$this->P;
		$v = (float) $P[0];
		$dst[0] = $v;
		$v = (float) $P[1];
		$dst[1] = $v;
		$dst[4] = $v;
		$v = (float) $P[2];
		$dst[2] = $v;
		$dst[8] = $v;
		$v = (float) $P[3];
		$dst[3] = $v;
		$dst[12] = $v;
		$v = (float) $P[5];
		$dst[5] = $v;
		$v = (float) $P[6];
		$dst[6] = $v;
		$dst[9] = $v;
		$v = (float) $P[7];
		$dst[7] = $v;
		$dst[13] = $v;
		$v = (float) $P[10];
		$dst[10] = $v;
		$v = (float) $P[11];
		$dst[11] = $v;
		$dst[14] = $v;
		$v = (float) $P[15];
		$dst[15] = $v;
	}

	public function variance(int $i): float
	{
		return $this->P[$i * 4 + $i];
	}
}
