<?php declare(strict_types=1);

/**
 * Generates fully unrolled sequential-form covariance kernels for small n
 * (BRIEF §4): src/Domain/Covariance/Kernels/Sequential{N}.php.
 *
 *   php tools/generate-kernels.php 2 4
 *
 * The generated classes are committed; re-run after changing this template.
 */

/** @var list<string> $argv */
$sizes = \array_slice($argv, 1);
if ($sizes === []) {
	$sizes = ['2', '4'];
}

foreach ($sizes as $arg) {
	$n = (int) $arg;
	if ($n < 2 || $n > 6) {
		\fwrite(\STDERR, "n must be in 2..6\n");
		exit(1);
	}
	$code = generate($n);
	$path = __DIR__ . "/../src/Domain/Covariance/Kernels/Sequential{$n}.php";
	if (!\is_dir(\dirname($path))) {
		\mkdir(\dirname($path), 0777, true);
	}
	\file_put_contents($path, $code);
	echo "wrote $path\n";
}

function idx(int $i, int $j, int $n): int
{
	return $i * $n + $j;
}

function generate(int $n): string
{
	$t = "\t";
	$lines = [];
	$L = static function (string $s) use (&$lines): void {
		$lines[] = $s;
	};

	$L('<?php declare(strict_types=1);');
	$L('');
	$L('namespace OpenCCK\\Kalman\\Domain\\Covariance\\Kernels;');
	$L('');
	$L('use OpenCCK\\Kalman\\Domain\\Contract\\CovarianceRepresentation;');
	$L('use OpenCCK\\Kalman\\Domain\\Contract\\SparseMotionModel;');
	$L('use OpenCCK\\Kalman\\Domain\\Exception\\DimensionMismatch;');
	$L('');
	$L('/**');
	$L(" * GENERATED by tools/generate-kernels.php — do not edit by hand.");
	$L(" * Fully unrolled sequential-form covariance for n = $n (§6.2 p.5):");
	$L(' * no loops, no function calls; identical algebra to DenseSequential.');
	$L(' */');
	$L("final class Sequential{$n} implements CovarianceRepresentation");
	$L('{');
	$L("{$t}/** @var array<int, float> n² */");
	$L("{$t}private array \$P;");
	$L('');
	$L("{$t}/** @var array<int, float> n */");
	$L("{$t}private array \$phi;");
	$L('');
	$L("{$t}private float \$hPh = 0.0;");
	$L('');
	$L("{$t}public function __construct()");
	$L("{$t}{");
	$L("{$t}{$t}\$this->P = \\array_fill(0, " . ($n * $n) . ', 0.0);');
	$L("{$t}{$t}\$this->phi = \\array_fill(0, $n, 0.0);");
	$L("{$t}}");
	$L('');
	$L("{$t}public function size(): int");
	$L("{$t}{");
	$L("{$t}{$t}return $n;");
	$L("{$t}}");
	$L('');

	// predictDense
	$L("{$t}public function predictDense(array \$F, array \$Q): void");
	$L("{$t}{");
	$L("{$t}{$t}\$P = &\$this->P;");
	for ($i = 0; $i < $n * $n; $i++) {
		$L("{$t}{$t}\$p$i = \$P[$i];");
	}
	// T = F P
	for ($i = 0; $i < $n; $i++) {
		for ($j = 0; $j < $n; $j++) {
			$terms = [];
			for ($k = 0; $k < $n; $k++) {
				$terms[] = '$F[' . idx($i, $k, $n) . '] * $p' . idx($k, $j, $n);
			}
			$L("{$t}{$t}\$t" . idx($i, $j, $n) . ' = ' . \implode(' + ', $terms) . ';');
		}
	}
	// P = T Fᵀ + Q, upper then mirror
	for ($i = 0; $i < $n; $i++) {
		for ($j = $i; $j < $n; $j++) {
			$terms = ['$Q[' . idx($i, $j, $n) . ']'];
			for ($k = 0; $k < $n; $k++) {
				$terms[] = '$t' . idx($i, $k, $n) . ' * $F[' . idx($j, $k, $n) . ']';
			}
			$L("{$t}{$t}\$v = " . \implode(' + ', $terms) . ';');
			$L("{$t}{$t}\$P[" . idx($i, $j, $n) . '] = $v;');
			if ($i !== $j) {
				$L("{$t}{$t}\$P[" . idx($j, $i, $n) . '] = $v;');
			}
		}
	}
	$L("{$t}}");
	$L('');

	// predictSparse
	$L("{$t}public function predictSparse(SparseMotionModel \$model, float \$dt, array &\$x, array \$Q): void");
	$L("{$t}{");
	$L("{$t}{$t}\$model->advanceInPlace(\$x, \$this->P, \$dt);");
	$L("{$t}{$t}\$P = &\$this->P;");
	for ($i = 0; $i < $n; $i++) {
		for ($j = $i; $j < $n; $j++) {
			$a = idx($i, $j, $n);
			$b = idx($j, $i, $n);
			if ($i === $j) {
				$L("{$t}{$t}\$P[$a] += \$Q[$a];");
			} else {
				$L("{$t}{$t}\$v = \$P[$a] + \$Q[$a];");
				$L("{$t}{$t}\$P[$a] = \$v;");
				$L("{$t}{$t}\$P[$b] = \$v;");
			}
		}
	}
	$L("{$t}}");
	$L('');

	// prepareScalar
	$L("{$t}public function prepareScalar(array \$h, float \$r): float");
	$L("{$t}{");
	$L("{$t}{$t}\$P = &\$this->P;");
	$L("{$t}{$t}\$phi = &\$this->phi;");
	for ($j = 0; $j < $n; $j++) {
		$L("{$t}{$t}\$h$j = \$h[$j] ?? 0.0;");
	}
	for ($i = 0; $i < $n; $i++) {
		$terms = [];
		for ($j = 0; $j < $n; $j++) {
			$terms[] = '$P[' . idx($i, $j, $n) . "] * \$h$j";
		}
		$L("{$t}{$t}\$f$i = " . \implode(' + ', $terms) . ';');
		$L("{$t}{$t}\$phi[$i] = \$f$i;");
	}
	$terms = [];
	for ($j = 0; $j < $n; $j++) {
		$terms[] = "\$h$j * \$f$j";
	}
	$L("{$t}{$t}\$hPh = " . \implode(' + ', $terms) . ';');
	$L("{$t}{$t}\$this->hPh = \$hPh;");
	$L("{$t}{$t}return \$hPh + \$r;");
	$L("{$t}}");
	$L('');

	$L("{$t}public function gain(): array");
	$L("{$t}{");
	$L("{$t}{$t}return \$this->phi;");
	$L("{$t}}");
	$L('');

	// commitScalar
	$L("{$t}public function commitScalar(float \$r): void");
	$L("{$t}{");
	$L("{$t}{$t}\$P = &\$this->P;");
	$L("{$t}{$t}\$phi = \$this->phi;");
	$L("{$t}{$t}\$inv = 1.0 / (\$this->hPh + \$r);");
	for ($i = 0; $i < $n; $i++) {
		$L("{$t}{$t}\$k$i = \$phi[$i] * \$inv;");
	}
	for ($i = 0; $i < $n; $i++) {
		for ($j = $i; $j < $n; $j++) {
			$a = idx($i, $j, $n);
			$b = idx($j, $i, $n);
			if ($i === $j) {
				$L("{$t}{$t}\$P[$a] -= \$k$i * \$phi[$j];");
			} else {
				$L("{$t}{$t}\$v = \$P[$a] - \$k$i * \$phi[$j];");
				$L("{$t}{$t}\$P[$a] = \$v;");
				$L("{$t}{$t}\$P[$b] = \$v;");
			}
		}
	}
	$L("{$t}}");
	$L('');

	$L("{$t}public function toDense(): array");
	$L("{$t}{");
	$L("{$t}{$t}return \$this->P;");
	$L("{$t}}");
	$L('');

	$L("{$t}public function fromDense(array \$P): void");
	$L("{$t}{");
	$L("{$t}{$t}if (\\count(\$P) !== " . ($n * $n) . ') {');
	$L("{$t}{$t}{$t}throw DimensionMismatch::forMatrix('P', " . ($n * $n) . ', \\count($P));');
	$L("{$t}{$t}}");
	$L("{$t}{$t}\$dst = &\$this->P;");
	for ($i = 0; $i < $n; $i++) {
		for ($j = $i; $j < $n; $j++) {
			$a = idx($i, $j, $n);
			$b = idx($j, $i, $n);
			$L("{$t}{$t}\$v = (float) \$P[$a];");
			$L("{$t}{$t}\$dst[$a] = \$v;");
			if ($i !== $j) {
				$L("{$t}{$t}\$dst[$b] = \$v;");
			}
		}
	}
	$L("{$t}}");
	$L('');

	$L("{$t}public function variance(int \$i): float");
	$L("{$t}{");
	$L("{$t}{$t}return \$this->P[\$i * $n + \$i];");
	$L("{$t}}");
	$L('}');
	return \implode("\n", $lines) . "\n";
}
